### ISSUE TITLE
Redirection loop with Nuage 5.x and vwire redirection targets

### ISSUE THREAD

**Issue by rvichery** [opensecuritycontroller/osc-nuage-plugin#41]
Starting with Nuage Networks VSP 5.x, vwire redirection target can't be used across subnets anymore (was actually an issue that got fixed in 5.x releases). This means that inspection ports must be in the same subnet as the protected workloads. This also introduce a redirection loop, the traffic exiting the egress inspection interface is sent back to the ingress inspection interface. 

To prevent this behavior, the plugin should implement a forwarding policy to normally forward the outgoing packet to the destination. 

When inspection ports are created, the workflow should be modified to:
  - create a policy groups containing both the ingress and egress interface of the VNF
  - create a new Forwarding Policy (reused for multiple VNF) with priority 1 (avoid conflict with the default policy created by the OpenStack plugin and has a higher precedence than the entries created by the inspection hook)
  - create a rule in the previously created policy to "FORWARD" (not redirect) traffic coming from the "VNF Policy Group" to ANY

When inspection ports are removed, the workflow should be modified to:
   - delete the forwarding entry rule
   - delete the policy group
   - delete the Forwarding Policy if there are no more rules in it

I propose that we keep track of the forwarding policy rule by adding the inspection interface IDs in the description of the rule. By doing that, we will be able to delete the right forwarding rule without much computation/rest calls.

**Comment by sudhirappaji** [comment]
@rvichery , I know this is already getting addressed. Please update when it is done, so that i can close this issue.

**Comment by rvichery** [comment]
The fix has been implemented and merged. I think we can close this issue
